services:
  postgres:
    container_name: gestion_vacantes_postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestion_vacantes