services:
  postgres:
    container_name: gestion_vacantes_postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DDB_USER}
      POSTGRES_PASSWORD: ${DDB_PASSWORD}
      POSTGRES_DB: ${DDB_NAME}