spring.application.name=gestor_vacantes
spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_vacantes
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

security.token.secret=JAVACANTES@123#