spring.application.name=gestor_vacantes
spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_vacantes
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret.company=${TOKEN_SECRET_COMPANY}
security.token.secret.candidate=${TOKEN_SECRET_CANDIDATE}

spring.config.import=optional:file:.env[.properties]
